# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeleMedML' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Parse'
  # Pods for TeleMedML

  target 'TeleMedMLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TeleMedMLUITests' do
    # Pods for testing
  end

end
